sudo: required
services:
  - docker
language: python
python:
    - "2.7"
before_install:
    - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
install: 
    - pip install -r requirements.txt
script: 
    - docker-compose up -d
    - docker-compose run gunicorn python manage.py migrate
    - docker-compose run gunicorn python manage.py loaddata building room
    - docker-compose run gunicorn python manage.py test
