sudo: required
services:
  - docker
language: python
python:
    - "2.7"
before_install:
    - pip install docker-compose
install: 
    - pip install -r requirements.txt
script: 
    - docker-compose up -d
    - docker-compose run gunicorn python manage.py migrate
    - docker-compose run gunicorn python manage.py loaddata building room
    - docker-compose run gunicorn python manage.py test
