language: python
python:
    - "2.7"
before_install:
    - pip install docker-compose
install: 
    - pip install -r requirements.txt
script: 
    - docker-compose up
    - docker-compose run gunicorn python manage.py test
