postgres:
  image: wbrefvem/conference-room-db:v3
gunicorn:
  image: wbrefvem/conference-room-api:v1
  working_dir: /code
  command: gunicorn -b 8000 -w 4 conferenceroom.wsgi -c /code/conferenceroom/settings.py --log-level info --access-logfile /code/logs/gunicorn_access.log --error-logfile /code/logs/gunicorn_error.log
  volumes:
    - .:/code
  links:
    - postgres
  ports:
    - "8000"
nginx:
  build: .
  command: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./staticfiles:/usr/share/nginx/html
  links:
    - gunicorn
  ports:
    - "8008:8008"