postgres:
  image: wbrefvem/conference-room-db:v3
gunicorn:
  image: wbrefvem/conference-room-api:v1
  command: gunicorn -b 8000 -w 4 conferenceroom.wsgi -c /code/conferenceroom/settings.py
  volumes:
    - .:/code
  links:
    - postgres
nginx:
  build: .
  command: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  links:
    - gunicorn
  ports:
    - "8008:8008"