db:
  image: wbrefvem/conference-room-db:v3
web:
  image: wbrefvem/conference-room-api:v1
  command: gunicorn -b 8000 -w 4 conferenceroom.wsgi -c /code/conferenceroom/settings.py
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db