postgres:
  image: wbrefvem/conference-room-db:v3
gunicorn:
  image: wbrefvem/conference-room-api:v1
  command: cd /code && gunicorn -b 8000 -w 4 conferenceroom.wsgi -c /code/conferenceroom/settings.py
  volumes:
    - .:/code
  links:
    - postgres
  ports:
    - "8000:8000"
nginx:
  build: .
  command: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./staticfiles:/usr/share/nginx/html
  links:
    - gunicorn
  ports:
    - "8008:8008"