postgres:
  image: wbrefvem/conference-room-db:v3
gunicorn:
  image: wbrefvem/conference-room-api:v1
  working_dir: /code
  command: gunicorn -b 0.0.0.0:8000 -w 4 conferenceroom.wsgi -c /code/conferenceroom/settings.py --log-level info
  volumes:
    - .:/code
  links:
    - postgres
nginx:
  image: wbrefvem/conference-room-nginx:v1
  command: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./staticfiles:/usr/share/nginx/html
  links:
    - gunicorn
  ports:
    - "8008:8008"