db:
  image: wbrefvem/conference-room-db:v2
web:
  image: wbrefvem/conference-room-api
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db